export const LOGGIN_TAGGLE = "LOGGIN_TAGGLE";
export const REGISTER_TAGGLE = "REGISTER_TAGGLE";
export const NEW_PROJECT_TAGGLE = "NEW_PROJECT_TAGGLE";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
